doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        # server_version: '13'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            LaSalleGroupSevenCoreDomainValueObject:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Core/Infrastructure/Persistence/Doctrine/Resources/Mapping'
                prefix: 'LaSalle\GroupSeven\Core\Domain\ValueObject'
            LaSalleGroupSevenLogDomain:
              is_bundle: false
              type: xml
              dir: '%kernel.project_dir%/src/Log/Infrastructure/Persistence/Doctrine/Resources/Mapping'
              prefix: 'LaSalle\GroupSeven\Log\Domain'
            LaSalleGroupSevenLogSummaryDomain:
              is_bundle: false
              type: xml
              dir: '%kernel.project_dir%/src/LogSummary/Infrastructure/Persistence/Doctrine/Resources/Mapping'
              prefix: 'LaSalle\GroupSeven\LogSummary\Domain'
            LaSalleGroupSevenUserDomain:
              is_bundle: false
              type: xml
              dir: '%kernel.project_dir%/src/User/Infrastructure/Persistence/Doctrine/Resources/Mapping'
              prefix: 'LaSalle\GroupSeven\User\Domain'
