version: '3.5'

services:
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    environment:
      discovery.type: "single-node"
    ports:
      - 9200:9200

  kibana:
    container_name: kibana
    depends_on:
      - elasticsearch
    image: docker.elastic.co/kibana/kibana:7.10.1
    environment:
      SERVER_NAME: localhost
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    ports:
      - 5601:5601


volumes:
  db_data:
