version: '3.5'

services:
  nginx:
    image: salleurl/nginx:1.19-alpine
    depends_on:
      - php-fpm
    ports:
      - 8080:80
    volumes:
      - type: bind
        source: ${PWD}
        target: /app
        read_only: true

  php-fpm:
    image: salleurl/php-fpm:8.0.3
    volumes:
      - type: bind
        source: ${PWD}
        target: /app
        read_only: false
    env_file:
      - ${PWD}/docker.env
