controllers:
    resource: ../../src/Controller/
    type: annotation

api_controllers:
    resource: ../../src/Controller/Api
    prefix: /api/
    type: annotation

user_controllers:
    resource: ../../src/Controller/User
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation
